add test for players display
marmelab/quarto-python pull request #3
Opened 2018-06-05 15:08 UTC by JulienMattiussi

I added tests for the "players" part of the display

2018-06-05 15:56 UTC, Kmaschta commented
Is it WIP or RFR ?

2018-06-06 07:00 UTC, jdemangeon requested changes

2018-06-06 07:00 UTC, jdemangeon commented on src/game/start.py
>      else:
No need for else because you return

2018-06-06 07:00 UTC, jdemangeon commented on src/game/start.py
> +    player_1 = selected_player_to_string(player_1, game_turn.player_one_active)
You can directly set 'Player N' string in selected_player_string first arg to avoid unecessary memory allocation

2018-06-06 07:00 UTC, jdemangeon commented on src/game/start.py
>      display_string = ''
You can return "player_1 + "     " + player_2" directly at the end without declare display_string at the top

2018-06-06 07:00 UTC, jdemangeon commented on src/game/tests/test_grid.py
> +    def test_grid_to_string_should_create_a_fixed_string(self):
What do you mean by "a_fixed_string" ?

2018-06-06 07:00 UTC, jdemangeon commented on src/game/tests/test_pieces.py
> +    def test_pieces_to_string_shouldnt_render_void_string(self):
Do you mean "empty_string" instead of "void_string" ?

2018-06-06 07:00 UTC, jdemangeon commented on src/game/tests/test_players.py
> +    def test_players_to_string_should_create_a_fixed_string(self):
Same, what's a "fixed_string" ?

2018-06-06 07:38 UTC, Kmaschta approved these changes

2018-06-06 08:44 UTC, Kmaschta approved these changes

2018-06-06 08:44 UTC, Kmaschta requested changes

2018-06-06 08:44 UTC, Kmaschta commented on src/game/tests/test_players.py
> +    def test_players_to_string_should_create_the reference_string(self):
There is typo in this function name

2018-06-06 08:53 UTC, jdemangeon commented on src/game/start.py
> +    player_1 = selected_player_to_string('Player 1', game_turn.player_one_active)
Far better :+1:

2018-06-06 09:11 UTC, jdemangeon approved these changes

2018-06-06 09:11 UTC, merged